name: Build Webcfg Component in Native Environment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: [ ubuntu-latest ]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      
      # Install the dependent packages
      - name: Install packages
        run: |
          sudo apt update
          sudo apt-get -y install valgrind libcunit1 libcunit1-doc libcunit1-dev libmsgpack-dev gcovr libtool xsltproc docbook-xsl uuid-dev libcurl4-openssl-dev lcov libmsgpack* libcjson-dev build-essential
          pip install codecov

      - name: native build
        run: |

          # Build component
          chmod +x build.sh
          ./build.sh
