name: Build Webcfg Component in Native Environment

on:
  push:
    branches: [ master, 'sprint/**', 'release/**', develop ]
  pull_request:
    branches: [ master, 'sprint/**', 'release/**', topic/RDK*, develop ]

jobs:
  build-webcfg-on-pr:
    name: Build webcfg component in github rdkcentral
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rdkcentral/docker-rdk-ci:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: native build
        run: |
          # Trust the workspace
          git config --global --add safe.directory '*'
          # Pull the latest changes for the native build system
          git submodule update --init --recursive --remote
          # Build component
          chmod +x build_tools_workflows/cov_docker_script/build_native.sh
          ./build_tools_workflows/cov_docker_script/build_native.sh ./cov_docker_script/component_config.json "$(pwd)"
        env:
          GITHUB_TOKEN: ${{ secrets.RDKCM_RDKE }}
